backport_dirs:
  vendor:
    - firmware/brcm
    - firmware/carrierconfig
    - firmware/dauntless
    - firmware/uecapconfig
    - firmware/google
backport_files:
  vendor:
    - firmware/1540.app
    - firmware/1540a.app
    - firmware/amss20.bin
    - firmware/aoc.bin
    - firmware/bcmdhd.cal_4383_a3
    - firmware/CPS4041_A0_02.bin
    - firmware/cs40l20.bin
    - firmware/Data.msc
    - firmware/fw_bcmdhd.bin
    - firmware/fw_bcmdhd.bin_4383_a3
    - firmware/fw_bcmdhd.bin_4390_b1
    - firmware/fw_bcmdhd.bin_4398_d0
    - firmware/fw_bcmdhd.map
    - firmware/fw_bcmdhd.map_4383_a3
    - firmware/fw_bcmdhd.map_4390_b1
    - firmware/fw_bcmdhd.map_4398_d0
    - firmware/g6.app
    - firmware/g7.app
    - firmware/g7a.app
    - firmware/gxp_callisto_fw_core0
    - firmware/gxp_callisto_fw_core1
    - firmware/gxp_callisto_fw_core2
    - firmware/gxp_fw_core0
    - firmware/gxp_fw_core1
    - firmware/gxp_fw_core2
    - firmware/gxp_fw_core3
    - firmware/gxp_ganymede_fw_core0
    - firmware/gxp_ganymede_fw_core1
    - firmware/gxp_ganymede_fw_core2
    - firmware/kepler.bin
    - firmware/mali_csffw-r54p0.bin
    - firmware/ntn_modem/modem.bin
    - firmware/ntn_modem/version.cfg
    - firmware/qm35_fw_pkg.bin
    - firmware/qm35_fw_pkg_prod.bin
    - firmware/st54l_conf.bin
    - firmware/rgx.fw.signed.71.2.2448.1212
    - firmware/rgx.sh.71.2.2448.1212
    - firmware/rdbl.img
    - firmware/seurat.bin
