includes:
  - apk.yml
  - backport.yml
  - file-exclusion.yml
  - file-inclusion.yml
  - kernel-cmdline.yml
  - overlay-inclusion.yml
  - overlay-removal.yml
  - replacement_modules.yml
  - sepolicy-inclusion.yml
  - sepolicy-exclusion.yml
  - synthetic-overlays.yml
  - sysconfig-exclusion.yml
  - sysconfig-inclusion.yml
  - sysprop-exclusion.yml
  - sysprop-inclusion.yml
  - vintf-inclusion.yml

device:
  vendor: google_devices
  has_cellular: true
  # Pixel phone model IDs are listed in the Network sections of:
  # https://support.google.com/pixelphone/answer/7158570?hl=en
  build_id: CP2A.260805.005
  backport_build_id: CP3A.260905.009
  backport_radio_firmware: true
  backport_bootloader_firmware: true
  backport_kernel: true
  gservices_flags_inclusions:
    prefix:
      - euicc.
      - euiccpixel.
  gservices_flags_exclusions:
    match:
      # EuiccSupportPixel is kept isolated from sandboxed GmsCore, so its GoogleApi clients for
      # UsageReporting / Clearcut are not expected to connect. This flag makes EuiccSupportPixel
      # schedule recurring metrics upload jobs that eventually attempt those GMS APIs.
      - euiccpixel.experiment.Ota__support_metrics_upload

filters:
  partitions:
    match:
      - vbmeta_system
      - vbmeta_vendor

extra_packages:
  - android.frameworks.stats-V3-ndk.vendor
